name: Test
on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test env
        env:
          FOO: ${{ secrets.DINGTALK_WEBHOOK }}
        run: echo "env set, length=${#FOO}"
